# oh-my-zsh installation directory
export ZSH="$HOME/.oh-my-zsh"

# theme
ZSH_THEME="michelebologna"

# autocompletion case sensitive
CASE_SENSITIVE="true"

# list of plugins
plugins=(git)

# run oh-my-zsh
source $ZSH/oh-my-zsh.sh

# options
setopt no_share_history
unsetopt share_history


# aliases
alias gdo="git difftool"
