#!/bin/sh

# RESOURCES ------------------------------------------------------------------------------

userresources=$HOME/.Xresources

if [ -f "$userresources" ]; then
    xrdb "$userresources"
fi


# STARTUP SCRIPTS ------------------------------------------------------------------------

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# WINDOW MANAGER -------------------------------------------------------------------------

# mapped directly on keyboard (VIA)
#setxkbmap -option caps:escape
~/.fehbg &
picom &
exec i3


# vim:cc=90
