autocmd VimEnter * :clearjumps


" ---- COMMAND ALIASES -------------------------------------------------------------------
command W       w
command Wa      wa
command Wq      wq
command Q       q
command Qa      qa


" ---- BUILT-IN EXTENSIONS ---------------------------------------------------------------
packadd comment
runtime ftplugin/man.vim


" ---- COMMAND MODE INPUT ----------------------------------------------------------------
cnoremap <C-A>      <Home>
cnoremap <C-E>      <End>
cnoremap <C-B>      <Left>
cnoremap <C-F>      <Right>
cnoremap <Esc>b     <S-Left>
cnoremap <Esc>f     <S-Right>

set cedit=^O


" ---- OPTIONS ---------------------------------------------------------------------------
syntax on
filetype plugin indent on

" command history size
set history=1000

" look
set number
set wildmenu
set wildoptions=pum
set showcmd
set laststatus=2
set scrolloff=1
set shortmess=filnxtToOSs
set cmdwinheight=40
set cursorline
set showtabline=2

" indent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent

" search
set hlsearch
set incsearch

" swap file
set noswapfile

" autoread file
set autoread

" split
set splitbelow
set splitright
set splitkeep=screen
set equalalways

" jumps
set jumpoptions=stack

" buffers
set hidden

" input
set backspace+=indent,eol,start
set noesckeys

" timeouts
set nottimeout
set timeout
set timeoutlen=1000
set ttimeoutlen=100
set updatetime=100

" fold
set foldmethod=syntax
set foldlevelstart=100

" it should be in cxx-cmake implemented and configured via settings.json
" yet for now stays
set cscopequickfix=s-,c-,d-,i-,t-,e-,a-


" ---- MAPPINGS --------------------------------------------------------------------------

" execute command (one line)
" it could execute multiple lines that are added to the list
nnoremap <C-L>rc 0v$hy:<C-R>"<CR>

" command window with immediate backward search
nnoremap q: q:<ESC>?
nnoremap q/ q/<ESC>?
nnoremap q? q?<ESC>?

" find but no jump
nnoremap <silent> *     :let @/= '\<' . expand('<cword>') . '\>' <bar> set hls <cr>
nnoremap <silent> g*    :let @/=expand('<cword>') <bar> set hls <cr>
vnoremap <silent> *     y:let @/= '\<' . "<C-R>"" . '\>'<CR> :set hls<CR>
vnoremap <silent> g*    y:let @/="<C-R>""<CR> :set hls<CR>

" replace
nnoremap <C-L><C-S>     :%s/\<<C-R><C-W>\>/
nnoremap g<C-L><C-S>    :%s/<C-R><C-W>/
vnoremap <C-L><C-S>     y:%s/\<<C-R>"\>/
vnoremap g<C-L><C-S>    y:%s/<C-R>"/

" go quicker
nnoremap <C-J> 10j
nnoremap <C-K> 10k

" remove line and don't update register
nnoremap dD "_dd

" quickfix window
nnoremap <silent> mc    :ccl<CR>

nnoremap <silent> [Q    :cfirst<CR>
nnoremap <silent> [q    :cprev<CR>
nnoremap <silent> ]q    :cnext<CR>
nnoremap <silent> ]Q    :clast<CR>

" location list
nnoremap <silent> [A    :lfirst<CR>
nnoremap <silent> [a    :lprev<CR>
nnoremap <silent> ]a    :lnext<CR>
nnoremap <silent> ]A    :llast<CR>

" auto close
inoremap {<CR>  {}<Left><CR><C-O>O
inoremap {;<CR> {};<Left><Left><CR><C-O>O

" tags
nnoremap m<C-I> :tag<CR>

" ---- COMMANDS --------------------------------------------------------------------------

command! -nargs=1 -complete=help H :enew | :set buftype=help | :keepalt h <args>
command! -nargs=1 Find vimgrep "\%^" <args> | :copen
command! -nargs=1 LFind lvimgrep "\%^" <args> | :lopen


" ---- PLUGINS ---------------------------------------------------------------------------

" ---- built-in ----------------------------------------------------------------------
let g:ft_man_open_mode = 'vert'


" ---- vim-nerdtree ----------------------------------------------------------------------
let NERDTreeMinimalUI               = 1
let NERDTreeWinSize                 = 40
let NERDTreeCascadeSingleChildDir   = 0
let NERDTreeMapMenu                 = 'M'

function! s:toggle_nerdtree()
    if !exists('g:NERDTree')
        return
    endif

    if g:NERDTree.IsOpen()
        :NERDTreeClose
    else
        :NERDTreeFind | :horizontal wincmd =
    endif
endfunction

" nnoremap <silent> <C-L><C-N>        :NERDTreeToggle \| :horizontal wincmd =<CR>
nnoremap <silent> <C-L><C-N>        :call <SID>toggle_nerdtree()<CR>
nnoremap <silent> <C-L>nf           :NERDTreeFind<CR>

autocmd BufEnter * if winnr('$') == 1
\                   && exists('b:NERDTree')
\                   && b:NERDTree.isTabTree() | quit | endif


" ---- vim-tagbar ------------------------------------------------------------------------
let g:tagbar_compact                = 2
let g:tagbar_position               = 'topleft vertical'
let g:tagbar_autoclose              = 1

nnoremap <silent> <C-N><C-T>        :TagbarToggle<CR>


" ---- vim-asyncrun ----------------------------------------------------------------------
let g:asyncrun_open                 = 12


" ---- vim-fugitive ----------------------------------------------------------------------
nnoremap <silent> mgl               :Git! -p log --graph --decorate<CR>
nnoremap <silent> <C-L><C-G>        :Gedit :<CR>
nnoremap <C-L>df                    :silent G fetch \| :G diff FETCH_HEAD HEAD<CR>


" ---- vim-cool --------------------------------------------------------------------------
let g:cool_total_matches            = 1



" ---- vim-ctrlp -------------------------------------------------------------------------
let g:ctrlp_match_current_file      = 1
let g:ctrlp_match_window            = 'bottom,order:ttb,min:30,max:30,results:50'
let g:ctrlp_working_path_mode       = ''
let g:ctrlp_bufname_mod             = ':~:p'
let g:ctrlp_bufpath_mod             = ''
let g:ctrlp_switch_buffer           = 'e'
let g:ctrlp_regexp                  = 1
let g:ctrlp_line_prefix             = '>>>> '
let g:ctrlp_user_command            = 'find .'
\                                   . ' -type f'
\                                   . ' -not -path "./build/*"'
\                                   . ' -not -path "./.git/*"'
\                                   . ' -printf "%P\n"'
let g:ctrlp_prompt_mappings         =
\ {
\   'PrtDeleteEnt()':   ['<c-q>'],
\   'ToggleType(1)':    ['<c-up>'],
\   'ToggleType(-1)':   ['<c-down>'],
\   'PrtCurRight()':    ['<c-f>'],
\   'PrtCurLeft()':     ['<c-b>'],
\ }

function! s:find_selected_tag(cmd)
    try
        let default_input           = get(g:, "ctrlp_default_input", "")
        let g:ctrlp_default_input   = getline("'<")[getpos("'<")[2]-1:getpos("'>")[2]-1]
        execute a:cmd
    finally
        if exists("default_input")
            let g:ctrlp_default_input = default_input
        endif
    endtry
endfunction

nnoremap <silent> mi    :CtrlPBuffer<CR>
nnoremap <silent> mP    :CtrlPBufTag<CR>
nnoremap <silent> mp    :CtrlPTag<CR>
xnoremap <silent> mP    :<c-u>call <SID>find_selected_tag("CtrlPBufTag")<CR>
xnoremap <silent> mp    :<c-u>call <SID>find_selected_tag("CtrlPTag")<CR>


" ---- vim-translate-shell ---------------------------------------------------------------
let g:translate_shell_language = ":pl"


" ---- vim-gitgutter ---------------------------------------------------------------------
let g:gitgutter_sign_allow_clobber              = 1
let g:gitgutter_sign_modified                   = 'M'
let g:gitgutter_sign_added                      = 'A'
let g:gitgutter_sign_removed                    = 'D'
let g:gitgutter_sign_removed_first_line         = 'D1'
let g:gitgutter_sign_removed_above_and_below    = 'D+'
let g:gitgutter_sign_modified_removed           = 'DM'


" ---- COLORS ----------------------------------------------------------------------------
colorscheme gruvbox
set background=dark


" ---- WINDOW VIEW -----------------------------------------------------------------------
function! s:save_window_view()
    if !exists("w:buffer_view")
        let w:buffer_view = {}
    endif
    let w:buffer_view[bufnr("%")] = winsaveview()
endfunction

function! s:restore_window_view()
    let buf = bufnr("%")
    if exists("w:buffer_view") && has_key(w:buffer_view, buf)
        let v = winsaveview()
        let is_file_begin = v.lnum == 1 && v.col == 0
        if is_file_begin && !&diff
            call winrestview(w:buffer_view[buf])
        endif
        unlet w:buffer_view[buf]
    endif
endfunction

if v:version >= 700
    autocmd BufLeave * call s:save_window_view()
    autocmd BufEnter * call s:restore_window_view()
endif


" ---- TABLINE ---------------------------------------------------------------------------
function! MyTabLabel(tabnr) abort
    let l:bufnr = tabpagebuflist(a:tabnr)[tabpagewinnr(a:tabnr) - 1]

    let l:modified = 0
    if getbufvar(l:bufnr, '&modified')
        let l:modified = 1
    endif

    let l:tablabel = ''
    let l:custom_tablabel = gettabvar(a:tabnr, 'tablabel', '')

    if empty(l:custom_tablabel)
        let l:bufname = bufname(l:bufnr)

        if empty(l:bufname)
            let l:tablabel = empty(&buftype) ? 'No Name' : '<' . &buftype . '>'
        else
            let l:tablabel = fnamemodify(l:bufname, ':t')
        endif
    else
        let l:tablabel .= l:custom_tablabel
    endif

    if l:modified
        let l:tablabel .= '*'
    endif

    return tabpagewinnr(a:tabnr, '$') . " " . l:tablabel
endfunction

function! MyTabLine() abort
    let l:tabline = ''

    for l:num in range(1, tabpagenr('$'))
        let l:tabline .= (l:num != tabpagenr()) ? '%#TabLine#' : '%#TabLineSel#'
        let l:tabline .= '%' . l:num . 'T %{MyTabLabel(' . l:num . ')} '
    endfor

    let l:tabline .= '%#TabLineFill#%T%='
    " let l:tabline .= repeat('%#TabLine#%999X[X]', l:num > 1)
    if ProsetIsProject()
        let l:tabline .= "%#TabLine#"
        \ . "(" . ProsetGetProjectName() . ":" . ProsetGetSettingsName() . ")"
    endif

    return l:tabline
endfunction


" ---- TAB RENAME ------------------------------------------------------------------------
function! TabRename(tablabel) abort
    let t:tablabel = a:tablabel
    execute 'redrawtabline'
endfunction

function! TabRename(tabnr, tablabel) abort
    call settabvar(a:tabnr, 'tablabel', a:tablabel)
    execute 'redrawtabline'
endfunction

function! s:rename_fugitive_tabname()
    let l:cmd_name      = "basename $(git rev-parse --show-toplevel)"
    let l:cmd_branch    = "git branch --show-current"
    let l:cmd_head      = "git rev-parse --short HEAD"

    let l:name_list     = systemlist(l:cmd_name)
    let l:branch_list   = systemlist(l:cmd_branch)

    let l:name = "N/A"
    let l:branch = "N/A"

    if !empty(l:name_list)
        let l:name = l:name_list[0]
    endif

    if !empty(l:branch_list)
        let l:branch = l:branch_list[0]
    else
        let l:head = systemlist(l:cmd_head)
        if !empty(l:head)
            let l:branch = l:head[0]
        endif
    endif

    call TabRename(1, "(" . l:name . ":" . l:branch . ")")
endfunction

if exists('+showtabline')
    command! -nargs=+ TabRename call TabRename(<f-args>)
  
    set tabline=%!MyTabLine()
    augroup fugitive_tabname
        autocmd!
        autocmd User FugitiveChanged,FugitiveIndex :call <SID>rename_fugitive_tabname()
    augroup END
endif
