#!/bin/bash

DIRECTORY="/tmp/lock_screen_image"
EXT=.png
SCREENSHOT_FILENAME="$DIRECTORY/lock_screen_image_`date +%F_%H%M%S`$EXT"
BLURRED_SCREENSHOT_FILENAME="`echo "$SCREENSHOT_FILENAME" | sed "s/$EXT//g"`-blurred$EXT"

mkdir -p "$DIRECTORY"

# echo $SCREENSHOT_FILENAME
# echo $BLURRED_SCREENSHOT_FILENAME

scrot -F "$SCREENSHOT_FILENAME"
convert "$SCREENSHOT_FILENAME" -blur 0x6 "$BLURRED_SCREENSHOT_FILENAME"

i3lock -n -i "$BLURRED_SCREENSHOT_FILENAME"
